use std::env;
use std::error::Error;
use std::fs;

// *******************************************************************************
// Notes:
// - The TODO's are not AI generated.
// - All code comments were generated by Gemini or ChatGPT after the fact.
//   - I prompted it to add comments to explain functions.
//   - It didn't do a great job of in-function comments.  I had to be explicit.
// - I also had AI generate the two tests to see what it would come up with.
// *******************************************************************************

// This function calculates a "wrapped" index, ensuring the result always
// stays within the range [0, modulus). It is commonly used for circular logic,
// like moving a player on a map where walking off the right edge brings you to
// the left edge.  Here is the breakdown of why it exists and what it does.
//
// The Problem it Solves:
// In Rust (like C, Java, and many others), the % operator calculates the remainder,
// not the mathematical modulus.
//
//     Mathematical Modulo: -1 mod 10 = 9 (Loops back to the end)
//     Rust Remainder (%): -1 % 10 = -1 (Stays negative)
//
// This function manually fixes that behavior so you never get a negative index.
//
// TODO: Is there a crate or std function that already does this? Look at rem_euclid().
// TODO: Add unit tests for this function.
fn wrap_mod(position: i64, adjustment: i64, modulus: i64) -> i64 {
    // Calculate new position with wrapping
    let new_position = position + adjustment;
    // Apply modulus to wrap around
    let mut wrapped_position = new_position % modulus;
    // Adjust for negative results to ensure it's within [0, modulus)
    if wrapped_position < 0 {
        wrapped_position += modulus;
    }
    wrapped_position
}

// Processes the movements directed by the input data and counts how many times position 0 is hit.
// TODO: Refactor out common code with `count_all_zero_hits`.
pub fn count_land_on_zero(input: &str) -> usize {
    let mut dial_position = 50;
    let mut zero_hits = 0;

    // Iterate over each line of input
    for raw_line in input.lines() {
        let trimmed_line = raw_line.trim();
        if trimmed_line.is_empty() {
            continue;
        }

        let left_or_right = trimmed_line.chars().next().unwrap_or(' ');
        let raw_distance = trimmed_line
            .get(1..) // Get the substring after the first character
            .map(str::trim) // Trim whitespace from the distance part
            .unwrap_or("0") // Default to "0" if there's no distance part
            .parse::<i64>(); // Parse the distance as an i64
        // Handle parsing result
        let num_clicks = match raw_distance {
            Ok(d) => d,
            Err(_) => continue,
        };

        // Determine direction
        let direction_adjusted_click_count = match left_or_right {
            'L' | 'l' => -num_clicks,
            'R' | 'r' => num_clicks,
            _ => 0,
        };

        // Skip if no movement
        if direction_adjusted_click_count == 0 {
            continue;
        }

        // Advance the dial by `direction_adjusted_click_count` (positive for R,
        // negative for L), wrapping into the range 0..100. If the dial ends up
        // exactly at 0 after this move, count that as a 'land on zero' hit.
        dial_position = wrap_mod(dial_position, direction_adjusted_click_count, 100);
        if dial_position == 0 {
            zero_hits += 1;
        }
    }

    zero_hits
}

// Processes the movements directed by the input data and counts how many times zero is 'crossed'
// during this movement.
fn count_zero_hits_for_rotation(
    dial_position: i64,
    direction_multiplier: i64,
    num_clicks: i64,
) -> usize {
    // Solve for the smallest positive click count in 1..=100 that lands on zero
    // (i.e. the first click during this rotation that will point at 0).
    let mut smallest_click_count_to_zero = if direction_multiplier == -1 {
        (dial_position % 100) as i64
    } else {
        ((100 - (dial_position % 100)) % 100) as i64
    };

    // If the remainder is 0 it means the dial is already at 0.
    // The next time it will point at 0 during a rotation is after a full loop
    // of 100 clicks — represent that as 100 so subsequent arithmetic counts
    // full-loop hits correctly (instead of using 0 which would be ambiguous).
    if smallest_click_count_to_zero == 0 {
        smallest_click_count_to_zero = 100;
    }

    // If the rotation contains the first click that lands on zero
    // (i.e. `num_clicks >= smallest_click_count_to_zero`), count that
    // hit plus any additional full 100-click loops inside the rotation.
    // Each extra full loop adds one more time the dial points at 0, so
    // we add `1 + floor((num_clicks - smallest_click_count_to_zero)/100)`.
    if num_clicks >= smallest_click_count_to_zero {
        1 + ((num_clicks - smallest_click_count_to_zero) / 100) as usize
    } else {
        0
    }
}

// Processes the movements directed by the input data and counts how many times position 0 is 'crossed'.
// TODO: Refactor out common code with `count_land_on_zero`.
pub fn count_all_zero_hits(input: &str) -> usize {
    let mut dial_position = 50;
    let mut zero_hits = 0;

    // Iterate over each line of input
    for raw_line in input.lines() {
        let trimmed_line = raw_line.trim();
        if trimmed_line.is_empty() {
            continue;
        }

        let left_or_right = trimmed_line.chars().next().unwrap_or(' ');
        let raw_distance = trimmed_line
            .get(1..) // Get the substring after the first character
            .map(str::trim) // Trim whitespace from the distance part
            .unwrap_or("0") // Default to "0" if there's no distance part
            .parse::<i64>(); // Parse the distance as an i64
        // Handle parsing result
        let num_clicks = match raw_distance { 
            Ok(d) => d,
            Err(_) => continue,
        };

        // Determine direction
        let direction_adjusted_click_count = match left_or_right {
            'L' | 'l' => -num_clicks,
            'R' | 'r' => num_clicks,
            _ => 0,
        };

        // Skip if no movement
        if direction_adjusted_click_count == 0 {
            continue;
        }

        // Determine direction multipier (+1 for R, -1 for L) and count zero hits for this rotation
        let direction_multiplier = if direction_adjusted_click_count > 0 { 1 } else { -1 };
        zero_hits += count_zero_hits_for_rotation(dial_position, direction_multiplier, num_clicks);

        // advance dial to new position
        dial_position = wrap_mod(dial_position, direction_multiplier * num_clicks, 100);
    }

    zero_hits
}

// TODO: Add unit tests for this function.
fn read_file() -> Result<String, Box<dyn Error>> {
    if let Some(input_file) = env::args().nth(1) {
        // Notice the guard (e.g., '?') that propagates errors to the caller.
        Ok(fs::read_to_string(input_file)?)
    } else {
        // The .into() converts the string literal into a Box<dyn Error>.
        Err("Missing input file as first arg.".into())
    }
}

fn main() {
    let input_data = read_file().expect("Failed to read input file");
    // Part 1: count times dial lands on zero at the end of rotations
    println!("\nLand on Zero: {}", count_land_on_zero(&input_data));
    // Part 2: count times dial points at zero during or at the end of rotations
    println!("Crossed Zero: {}", count_all_zero_hits(&input_data));
}

// TODO: Share the input between these two tests to avoid duplication.
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn counts_zero_hits_for_given_input() {
        let input = "\
L68
L30
R48
L5
R60

L55
L1
L99
R
R14
L82";

        assert_eq!(count_land_on_zero(input), 3);
    }

    #[test]
    fn counts_all_zero_hits_for_given_input() {
        let input = "\
L68
L30
R48
L5
R60

L55
L1
L99
R
R14
L82";

        assert_eq!(count_all_zero_hits(input), 6);
    }
}
